/**
 * What an index is allowed to say.
 *
 * This is a contract with people who do not have this codebase — anyone publishing a registry — so
 * it is checked here rather than only when a fetch happens to run. It moved from `@plume/core` when
 * the worker started needing the same answers: a contract enforced in one of the three places that
 * depend on it is a contract the other two are free to drift from.
 */

import assert from "node:assert/strict";
import { test } from "node:test";

import { isValidId, normalise, readIndex, slugOf } from "../src/entry.ts";

const base = { id: "x", name: "X", repository: "https://github.com/o/r.git" };

test("a plugin entry survives intact, logo and all", () => {
	const entry = normalise({ ...base, kind: "plugin", logo: "https://github.com/o.png?size=128" });
	assert.equal(entry?.kind, "plugin");
	assert.equal(entry?.logo, "https://github.com/o.png?size=128");
});

test("kind is taken from the index when stated", () => {
	assert.equal(normalise({ ...base, kind: "mcp" })?.kind, "mcp");
	assert.equal(normalise({ ...base, kind: "skill" })?.kind, "skill");
	assert.equal(normalise({ ...base, kind: "plugin" })?.kind, "plugin");
});

test("and inferred only when it is not", () => {
	// Naming an npm package is how an MCP server is distributed; nothing else in the format implies one.
	assert.equal(normalise({ ...base, package: "@scope/thing" })?.kind, "mcp");
	assert.equal(normalise(base)?.kind, "plugin");
	// A skill collection is never guessed at — it has no distinguishing field.
	assert.notEqual(normalise(base)?.kind, "skill");
});

test("nonsense in `kind` falls back to the inference rather than through", () => {
	assert.equal(normalise({ ...base, kind: "banana" })?.kind, "plugin");
	assert.equal(normalise({ ...base, kind: "banana", package: "p" })?.kind, "mcp");
});

test("a sub-path is kept, which is how one repository ships many bundles", () => {
	assert.equal(normalise({ ...base, path: "skills" })?.path, "skills");
	assert.equal(normalise(base)?.path, undefined);
});

test("a missing id is derived from the name rather than rejected", () => {
	// An index that named the thing has said enough; requiring both would reject entries for a
	// field the publisher had no reason to think mattered.
	assert.equal(normalise({ name: "Agent Browser", repository: "https://github.com/o/r.git" })?.id, "agent-browser");
});

test("an entry with nowhere to clone from is dropped", () => {
	assert.equal(normalise({ id: "x", name: "X" }), null, "no repository");
	assert.equal(normalise({ ...base, repository: "ftp://example.com/x" }), null, "not a git scheme");
	assert.equal(normalise(null), null);
	assert.equal(normalise("a string"), null);
});

test("a logo that is not http(s) is dropped rather than rendered", () => {
	// It goes straight into an <img src>; `javascript:` there is the whole reason this check exists.
	assert.equal(normalise({ ...base, logo: "javascript:alert(1)" })?.logo, undefined);
	assert.equal(normalise({ ...base, logo: "http://x/y.png" })?.logo, "http://x/y.png");
});

test("a tarball must be https, because it gets downloaded and unpacked", () => {
	assert.equal(normalise({ ...base, tarball: "http://x/y.tgz" })?.tarball, undefined, "plain http");
	assert.equal(normalise({ ...base, tarball: "https://x/y.tgz" })?.tarball, "https://x/y.tgz");
});

test("a sha256 that is not one is dropped, not carried to fail a comparison later", () => {
	const good = "a".repeat(64);
	assert.equal(normalise({ ...base, sha256: good })?.sha256, good);
	assert.equal(normalise({ ...base, sha256: "deadbeef" })?.sha256, undefined, "too short");
	assert.equal(normalise({ ...base, sha256: "z".repeat(64) })?.sha256, undefined, "not hex");
	// Upper case is the same hash; normalising it means one comparison rather than two.
	assert.equal(normalise({ ...base, sha256: "A".repeat(64) })?.sha256, good);
});

test("counts that are not counts do not become counts", () => {
	assert.equal(normalise({ ...base, skillCount: 8 })?.skillCount, 8);
	assert.equal(normalise({ ...base, skillCount: -1 })?.skillCount, undefined);
	assert.equal(normalise({ ...base, skillCount: "eight" })?.skillCount, undefined);
	// snake_case too: the index is generated by scripts that were not all written here.
	assert.equal(normalise({ ...base, skill_count: 3 })?.skillCount, 3);
});

test("an index reads from any of the four container shapes", () => {
	const one = [{ ...base, id: "a", name: "A" }];
	assert.equal(readIndex(one).entries.length, 1, "bare array");
	assert.equal(readIndex({ plugins: one }).entries.length, 1, "plugins");
	assert.equal(readIndex({ collections: one }).entries.length, 1, "collections");
	assert.equal(readIndex({ entries: one }).entries.length, 1, "entries");
	assert.equal(readIndex({ name: "Mine", plugins: one }).name, "Mine");
});

test("an index keeps the entries it can read and drops the rest", () => {
	// One bad row should cost that row, not the catalogue.
	const index = readIndex({ plugins: [base, { name: "no repo" }, null, { ...base, id: "b" }] });
	assert.deepEqual(
		index.entries.map((entry) => entry.id),
		["x", "b"],
	);
});

test("an index that is not a list is an error, not an empty catalogue", () => {
	// Silently showing nothing is how a broken index looks exactly like an empty one.
	assert.throws(() => readIndex({ plugins: "nope" }));
	assert.throws(() => readIndex(42));
});

test("an id has to survive being a directory name and a URL segment", () => {
	assert.ok(isValidId("agent-browser"));
	assert.ok(isValidId("a.b_c-1"));
	assert.ok(!isValidId(""), "empty");
	assert.ok(!isValidId("../etc"), "climbs out");
	assert.ok(!isValidId("a..b"), "contains ..");
	assert.ok(!isValidId("a/b"), "separator");
	assert.ok(!isValidId(".hidden"), "leading dot");
	assert.ok(!isValidId("A".repeat(65)), "too long");
});

test("slugging a name gives something an id check accepts", () => {
	assert.equal(slugOf("Agent Browser"), "agent-browser");
	// The trailing run of punctuation collapses to one dash, which is then trimmed off the end.
	assert.equal(slugOf("Chrome DevTools!!"), "chrome-devtools");
	assert.ok(isValidId(slugOf("Sequential Thinking")));
});

test("compatibility is read off the archive, and a plugin manifest only counts for a plugin", async () => {
	const { clientsFor } = await import("../src/clients.ts");
	const none = { skills: false, mcp: false, claudePlugin: false, lyraPlugin: false, codexPlugin: false };

	// Skills are the portable case: every agent that reads SKILL.md can install them.
	assert.deepEqual(clientsFor("skill", { ...none, skills: true }), ["claude-code", "codex", "pi", "lyra"]);

	/*
	 * The bug this exists to prevent. Context7 is a `.mcp.json` plus a `.lyra-plugin/` directory
	 * holding a name and an icon — metadata, not a plugin. Counting that directory as evidence
	 * advertised it as installable into Lyra and Codex as a plugin, which it is not.
	 */
	assert.deepEqual(clientsFor("mcp", { ...none, mcp: true, lyraPlugin: true }), ["mcp"]);

	// For something that really is a plugin, the manifest does say which product's format it is.
	assert.deepEqual(clientsFor("plugin", { ...none, skills: true, lyraPlugin: true }), [
		"claude-code",
		"codex",
		"pi",
		"lyra",
	]);
	assert.deepEqual(clientsFor("plugin", { ...none, claudePlugin: true }), ["claude-code"]);

	// Codex is never inferred from Lyra's directory, only from its own.
	assert.deepEqual(clientsFor("plugin", { ...none, lyraPlugin: true }), ["lyra"]);
	assert.deepEqual(clientsFor("plugin", { ...none, codexPlugin: true }), ["codex"]);

	// Nothing recognisable claims nothing, rather than claiming everything.
	assert.deepEqual(clientsFor("plugin", none), []);
});

test("a bundle with an archive but no repository is kept", () => {
	/*
	 * An uploaded private bundle has no repository — that is what makes it private. Requiring one
	 * dropped those entries inside `readIndex`, so the platform listed them and the client behaved as
	 * though they did not exist: the catalogue said 11, the app saw 10, and nothing said why.
	 */
	const entry = normalise({
		id: "secret-notes",
		name: "内部笔记",
		repository: "",
		tarball: "https://market.example/v1/download/secret-notes/1.0.0?token=abc",
		kind: "plugin",
	});
	assert.equal(entry?.id, "secret-notes");
	assert.equal(entry?.repository, "");
	assert.ok(entry?.tarball);
});

test("with neither, there is nowhere to install from", () => {
	assert.equal(normalise({ id: "nothing", name: "空的" }), null);
});

test("a repository that is not a git URL is still refused", () => {
	// The relaxation is "may be absent", not "may be anything".
	assert.equal(normalise({ id: "x", name: "x", repository: "ftp://example.com/x.git" }), null);
	assert.equal(normalise({ id: "x", name: "x", repository: "javascript:alert(1)" }), null);
});

test("一台 MCP 服务要的钥匙跟着索引走，名字不合规的、链接不是 https 的丢掉", () => {
	const entry = normalise({
		...base,
		kind: "mcp",
		env: [
			{ name: "BRAVE_API_KEY", description: " Brave 搜索的 API key ", url: "https://brave.com/search/api/" },
			{ name: "OPTIONAL_REGION", optional: true, url: "javascript:alert(1)" },
			{ name: "not a name" },
			"BRAVE_API_KEY",
		],
		keywords: ["search", "", 3, "web"],
	});
	assert.deepEqual(entry?.needs, [
		{ name: "BRAVE_API_KEY", description: "Brave 搜索的 API key", url: "https://brave.com/search/api/" },
		{ name: "OPTIONAL_REGION", optional: true },
	]);
	assert.deepEqual(entry?.keywords, ["search", "web"]);
	assert.equal(normalise({ ...base, needs: [] })?.needs, undefined, "空的就是没有");
});

test("where the logo came from survives when it is one of the four, and is dropped otherwise", () => {
	assert.equal(normalise({ ...base, iconSource: "uploaded" })?.iconSource, "uploaded");
	assert.equal(normalise({ ...base, iconSource: "bundled" })?.iconSource, "bundled");
	assert.equal(normalise({ ...base, iconSource: "made-up" })?.iconSource, undefined);
	assert.equal(normalise({ ...base })?.iconSource, undefined);
});

test("the fields a maintainer curated come through, and nothing that is not a field name", () => {
	assert.deepEqual(normalise({ ...base, curated: ["name", "description", 3, null] })?.curated, ["name", "description"]);
	assert.equal(normalise({ ...base, curated: "name" })?.curated, undefined);
});
