export type MobileLocale = "zh-CN" | "en";

export const MOBILE_LOCALES = ["zh-CN", "en"] as const satisfies readonly MobileLocale[];

const zhCN = {
	"home.title": "连接你的桌面端", "home.body": "Plume 的文件、终端和 MCP 都运行在电脑上。连接后，手机会显示同一个 Plume 界面。", "home.start": "开始配对", "home.hint": "在桌面端打开「设置 → 移动端同步」，启用服务后扫描二维码。",
	"pair.intro": "在桌面端打开「设置 → 移动端同步」并启用服务，那里会出现一张二维码。", "pair.scan": "扫码连接", "pair.paste": "或从剪贴板粘贴配对链接", "pair.manual": "扫不了的话，也可以手动填写下面三项。", "pair.address": "局域网地址", "pair.port": "端口", "pair.token": "配对令牌", "pair.tokenPlaceholder": "桌面端生成的令牌", "pair.connect": "连接", "pair.disconnect": "断开连接", "pair.clipboardMissing": "剪贴板里没有配对链接（{reason}）", "pair.pastedRelay": "已从剪贴板读取配对信息（经中转）", "pair.pasted": "已从剪贴板读取配对信息", "pair.required": "请填写完整的地址、端口和令牌", "pair.relayFailed": "连不上中转 {address}，请确认地址无误、服务在运行。", "pair.directFailed": "无法连接到 {address}，请确认电脑和手机在同一网络，且同步服务已启用。", "pair.tokenWrong": "令牌不正确，请在桌面端重新复制。",
	"scan.permission": "需要相机权限", "scan.permissionDetail": "扫描桌面端「移动端同步」页面上的二维码即可完成配对。相机只用于这一件事。", "scan.allow": "允许使用相机", "scan.settings": "去系统设置里开启", "scan.manual": "改用手动输入", "scan.connecting": "正在连接…", "scan.unreachable": "连不上 {address}，检查两台设备是否在同一网络", "scan.rejected": "令牌被拒绝，请在桌面端重新生成二维码", "scan.aim": "对准桌面端的二维码", "scan.path": "设置 → 移动端同步", "scan.manualAddress": "扫不了？手动输入地址",
	"desk.exitAgain": "再按一次退出", "desk.none": "还没有连接桌面端", "desk.pair": "去配对", "desk.unsupported": "不支持的原生操作", "desk.openFailed": "打不开桌面端", "desk.response": "桌面端返回 {status}", "desk.loading": "正在加载桌面端界面…", "desk.reconnecting": "正在恢复桌面连接…", "desk.failed": "连不上桌面端", "desk.retry": "重试", "desk.repair": "重新配对",
} as const;

type MobileMessageKey = keyof typeof zhCN;
type MobileCatalog = Record<MobileMessageKey, string>;

const catalogs: Record<MobileLocale, MobileCatalog> = {
	"zh-CN": zhCN,
	en: {
		"home.title": "Connect your desktop", "home.body": "Plume's files, terminal, and MCP run on your computer. Once connected, your phone shows the same Plume interface.", "home.start": "Start pairing", "home.hint": "Open Settings → Mobile sync on the desktop, enable the service, then scan the QR code.",
		"pair.intro": "Open Settings → Mobile sync on the desktop and enable the service. A QR code will appear there.", "pair.scan": "Scan to connect", "pair.paste": "Or paste a pairing link", "pair.manual": "If scanning is unavailable, enter the three values below.", "pair.address": "Local network address", "pair.port": "Port", "pair.token": "Pairing token", "pair.tokenPlaceholder": "Token generated by the desktop", "pair.connect": "Connect", "pair.disconnect": "Disconnect", "pair.clipboardMissing": "No pairing link found on the clipboard ({reason})", "pair.pastedRelay": "Pairing details pasted from clipboard (via relay)", "pair.pasted": "Pairing details pasted from clipboard", "pair.required": "Enter the complete address, port, and token", "pair.relayFailed": "Could not reach relay {address}. Check the address and make sure the service is running.", "pair.directFailed": "Could not reach {address}. Make sure both devices are on the same network and sync is enabled.", "pair.tokenWrong": "The token is incorrect. Copy it again from the desktop.",
		"scan.permission": "Camera access needed", "scan.permissionDetail": "Scan the QR code on the desktop Mobile sync page to pair. The camera is only used for this.", "scan.allow": "Allow camera access", "scan.settings": "Open system settings", "scan.manual": "Enter details manually", "scan.connecting": "Connecting…", "scan.unreachable": "Could not reach {address}. Check that both devices are on the same network.", "scan.rejected": "The token was rejected. Generate a new QR code on the desktop.", "scan.aim": "Point at the desktop QR code", "scan.path": "Settings → Mobile sync", "scan.manualAddress": "Can't scan? Enter the address",
		"desk.exitAgain": "Press again to exit", "desk.none": "No desktop connected", "desk.pair": "Pair now", "desk.unsupported": "Unsupported native action", "desk.openFailed": "Could not open the desktop", "desk.response": "Desktop returned {status}", "desk.loading": "Loading the desktop interface…", "desk.reconnecting": "Restoring the desktop connection…", "desk.failed": "Could not connect to the desktop", "desk.retry": "Retry", "desk.repair": "Pair again",
	},
};

export function resolveMobileLocale(language: string): MobileLocale {
	// Same families as the desktop catalog (docs/architecture/i18n.md): every Chinese region reads
	// Simplified Chinese, everything else English, so the shell and the page it hosts agree.
	const normalized = language.replaceAll("_", "-").toLowerCase();
	return normalized === "zh" || normalized.startsWith("zh-") ? "zh-CN" : "en";
}

export function mobileTranslator(language = Intl.DateTimeFormat().resolvedOptions().locale) {
	const catalog = catalogs[resolveMobileLocale(language)];
	return (key: MobileMessageKey, variables?: Readonly<Record<string, string | number>>): string => {
		const template = catalog[key];
		if (!variables) return template;
		return template.replace(/\{([^}]+)\}/g, (match, name: string) => {
			const value = variables[name];
			return value === undefined ? match : String(value);
		});
	};
}
